version: 2.1

jobs:
  checkoutEtTests:
    docker:
      - image: cimg/node:22.09
    steps:
      - checkout
      - run:
          name: Installer dépendances
          command:
            cd ..
            npm install
      - run:
          name: Exécuter tests
          command:
            cd ..
            npm run test

workflows:
  labo_01:
    jobs:
      - checkoutEtTests