version: 2.1

orbs:
  node: circleci/node@4.0.0

jobs:
  checkoutEtTests:
    executor:
      name: node/default 
      tag: '22.9'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test

workflows:
  labo_01:
    jobs:
      - checkoutEtTests
