version: 2.1

orbs:
  node: circleci/node@2.9

jobs:
  checkoutEtTests:
    executor:
      name: node/default 
      tag: '16.13'
    steps:
      - checkout
      - run:
          name: Installer les dépendances backend
          command: |
            cd 3w5-h25-L01-backend 
            npm install
      - run:
          name: Exécuter les tests backend
          command: |
            cd 3w5-h25-L01-backend
            npm run test

workflows:
  labo_01:
    jobs:
      - checkoutEtTests
