version: 2.1

jobs:
  checkoutEtTests:
    docker:
      - image: cimg/node:22.9
    steps:
      - run:
          name: cloner, installer dependances et t
          command: |
            git clone https://github.com/jeyriss974/3w5-h25-L01-backend.git
            cd 3w5-h25-L01-backend
            npm install
            npm run test

workflows:
  labo_01:
    jobs:
      - checkoutEtTests