version: 2.1

jobs:
  checkoutEtTests:
    docker:
      - image: cimg/node:22.9
    steps:
      - run:
          name: Installer dépendances
          command:
            git clone https://github.com/jeyriss974/3w5-h25-L01-backend.git
      - run:
          name: Installer dépendances
          command:
            npm install
      - run:
          name: Exécuter tests
          command:
            npm run test

workflows:
  labo_01:
    jobs:
      - checkoutEtTests