version: 2.1

orbs:
  node: circleci/node@4.0.0

jobs:
  checkoutEtTests:
    executor:
      name: node/default 
      tag: '16.13'
    steps:
      - checkout
      - run:
          name: Installer les dépendances backend
          command:
            npm install
      - run:
          name: Exécuter les tests backend
          command:
            npm run test

workflows:
  labo_01:
    jobs:
      - checkoutEtTests
